---
name: Deploy Frontend to AWS Amplify

on:
  push:
    branches:
      - main
    paths:
      - 's4-ui/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    name: Deploy to AWS Amplify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 's4-ui/package-lock.json'

      - name: Install dependencies
        working-directory: s4-ui
        run: npm ci

      - name: Create production environment file
        working-directory: s4-ui
        run: |
          cat > .env.production << EOL
# API URL (required)
REACT_APP_API_URL=https://api.s4-storage.com

# Website URL (required for authentication)
REACT_APP_WEBSITE_DOMAIN=https://app.s4-storage.com

# Environment
REACT_APP_ENV=production

# SuperTokens Configuration
REACT_APP_SUPERTOKENS_CONNECTION_URI="${{ secrets.SUPERTOKENS_CONNECTION_URI }}"
REACT_APP_SUPERTOKENS_API_KEY="${{ secrets.SUPERTOKENS_API_KEY }}"
REACT_APP_GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}"
REACT_APP_GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}"

# Optional Settings
REACT_APP_ENABLE_ANALYTICS=true
REACT_APP_FILE_SIZE_LIMIT=10485760
EOL
          cp .env.production .env
          echo "Build timestamp: $(date)" >> .env

      - name: Build frontend
        working-directory: s4-ui
        run: npm run build

      - name: Deploy to AWS Amplify
        run: |
          echo "Deploying to AWS Amplify app ${{ secrets.AMPLIFY_APP_ID }}"
          aws amplify start-job \
            --app-id ${{ secrets.AMPLIFY_APP_ID }} \
            --branch-name main \
            --job-type RELEASE
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
