---
name: Deploy Frontend to AWS Amplify

on:
  push:
    branches:
      - main
    paths:
      - 's4-ui/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    name: Deploy to AWS Amplify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 's4-ui/package-lock.json'

      - name: Install dependencies
        working-directory: s4-ui
        run: npm ci

      - name: Create production environment file
        working-directory: s4-ui
        run: |
          cp .env.production .env
          echo "Build timestamp: $(date)" >> .env

      - name: Build frontend
        working-directory: s4-ui
        run: npm run build

      - name: Deploy to AWS Amplify
        uses: aws-actions/amplify-cli-action@master
        with:
          amplify_command: publish
          amplify_env: prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
